# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='status1',
            field=models.CharField(default='test', max_length=3),
        ),
    ]
