# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0002_auto_20180109_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='status1',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status10',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status11',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status12',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status13',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status14',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status15',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status16',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status17',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status18',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status19',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status2',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status20',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status3',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status4',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status5',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status6',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status7',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status8',
            field=models.CharField(default='enm', max_length=3),
        ),
        migrations.AlterField(
            model_name='day',
            name='status9',
            field=models.CharField(default='enm', max_length=3),
        ),
    ]
