# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0003_auto_20180109_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='id',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
