# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0004_auto_20180109_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('houseName', models.CharField(default='house', max_length=50, primary_key=True, serialize=False)),
                ('inmate1', models.CharField(default='empty', max_length=20)),
                ('inmate2', models.CharField(default='empty', max_length=20)),
                ('inmate3', models.CharField(default='empty', max_length=20)),
                ('inmate4', models.CharField(default='empty', max_length=20)),
                ('inmate5', models.CharField(default='empty', max_length=20)),
                ('inmate6', models.CharField(default='empty', max_length=20)),
                ('inmate7', models.CharField(default='empty', max_length=20)),
                ('inmate8', models.CharField(default='empty', max_length=20)),
                ('inmate9', models.CharField(default='empty', max_length=20)),
                ('inmate10', models.CharField(default='empty', max_length=20)),
                ('inmate11', models.CharField(default='empty', max_length=20)),
                ('inmate12', models.CharField(default='empty', max_length=20)),
                ('inmate13', models.CharField(default='empty', max_length=20)),
                ('inmate14', models.CharField(default='empty', max_length=20)),
                ('inmate15', models.CharField(default='empty', max_length=20)),
                ('inmate16', models.CharField(default='empty', max_length=20)),
                ('inmate17', models.CharField(default='empty', max_length=20)),
                ('inmate18', models.CharField(default='empty', max_length=20)),
                ('inmate19', models.CharField(default='empty', max_length=20)),
                ('inmate20', models.CharField(default='empty', max_length=20)),
            ],
        ),
    ]
