# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0006_auto_20180111_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='inmate1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate10',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate11',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate12',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate13',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate14',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate15',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate16',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate17',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate18',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate19',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate20',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate4',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate5',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate6',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate7',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate8',
        ),
        migrations.RemoveField(
            model_name='house',
            name='inmate9',
        ),
        migrations.AddField(
            model_name='house',
            name='student1',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student10',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student11',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student12',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student13',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student14',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student15',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student16',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student17',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student18',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student19',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student2',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student20',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student3',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student4',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student5',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student6',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student7',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student8',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='student9',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
