# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0006_auto_20180111_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='inmate1',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate10',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate11',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate12',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate13',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate14',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate15',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate16',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate17',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate18',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate19',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate2',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate20',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate3',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate4',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate5',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate6',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate7',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate8',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='inmate9',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
