# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0007_auto_20180111_1653'),
        ('studentspot', '0007_auto_20180111_1650'),
    ]

    operations = [
    ]
