# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0007_auto_20180111_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='days_forward',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
