# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0008_house_days_forward'),
        ('studentspot', '0008_merge_20180111_2357'),
    ]

    operations = [
    ]
