# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0007_auto_20180112_1434'),
        ('studentspot', '0009_merge_20180112_0018'),
    ]

    operations = [
    ]
