# Generated by Django 2.0 on 2018-01-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0009_mymodel'),
        ('studentspot', '0010_merge_20180112_1440'),
    ]

    operations = [
    ]
