# Generated by Django 2.0 on 2018-01-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0011_merge_20180115_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='house',
            name='days_forward',
        ),
    ]
