# Generated by Django 2.0 on 2018-01-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0012_auto_20180115_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='status1',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status10',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status11',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status12',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status13',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status14',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status15',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status16',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status17',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status18',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status19',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status20',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status4',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status5',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status6',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status7',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status8',
        ),
        migrations.RemoveField(
            model_name='day',
            name='status9',
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
