# Generated by Django 2.0 on 2018-01-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentspot', '0013_auto_20180115_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='user',
            new_name='student',
        ),
    ]
